City: Delhi
Pollutants: all
Study period: 1/1/2015 - 12/31/2016
Dataset: Climate, Pollutants
Resources: Kaggle.com, API: OpenAQ, Archived CSV files

In [1]:
#Dependencies
import pandas as pd
import matplotlib.pyplot as plt
from sqlalchemy import create_engine
import requests
from datetime import date, datetime, timedelta

In [2]:
weather_file = "./dataset/Cleaned Data - Delhi - 2015-2016.csv"
weather_df = pd.read_csv(weather_file)
weather_df.head()

       date  meantemp  humidity  wind_speed  meanpressure
0  1/1/2015    14.750    72.000      0.9250      1017.500
1  1/2/2015    14.875    96.625      3.0125      1017.875
2  1/3/2015    15.125    92.000      0.9250      1017.375
3  1/4/2015    14.125    78.750      9.5125      1019.625
4  1/5/2015    14.000    69.375     15.0500      1016.000

In [ ]:
# pollutant_file = "./Dataset/LicensePremise.csv"
# pollutant_df = pd.read_csv(pollutant_file)
# pollutant_df.head()

In [3]:
#Dataset Cleaning
#start date
sdate = date(2016, 4, 25) 

#end date
edate = date(2017, 4, 24)

#as time delta
delta = edate - sdate

datadays = []

for i in range(delta.days + 1):
    value = sdate + timedelta(days=i)
    str(value)
    datadays.append(value)
    
datadays

[datetime.date(2016, 4, 25),
 datetime.date(2016, 4, 26),
 datetime.date(2016, 4, 27),
 datetime.date(2016, 4, 28),
 datetime.date(2016, 4, 29),
 datetime.date(2016, 4, 30),
 datetime.date(2016, 5, 1),
 datetime.date(2016, 5, 2),
 datetime.date(2016, 5, 3),
 datetime.date(2016, 5, 4),
 datetime.date(2016, 5, 5),
 datetime.date(2016, 5, 6),
 datetime.date(2016, 5, 7),
 datetime.date(2016, 5, 8),
 datetime.date(2016, 5, 9),
 datetime.date(2016, 5, 10),
 datetime.date(2016, 5, 11),
 datetime.date(2016, 5, 12),
 datetime.date(2016, 5, 13),
 datetime.date(2016, 5, 14),
 datetime.date(2016, 5, 15),
 datetime.date(2016, 5, 16),
 datetime.date(2016, 5, 17),
 datetime.date(2016, 5, 18),
 datetime.date(2016, 5, 19),
 datetime.date(2016, 5, 20),
 datetime.date(2016, 5, 21),
 datetime.date(2016, 5, 22),
 datetime.date(2016, 5, 23),
 datetime.date(2016, 5, 24),
 datetime.date(2016, 5, 25),
 datetime.date(2016, 5, 26),
 datetime.date(2016, 5, 27),
 datetime.date(2016, 5, 28),
 datetime.date(2016, 5, 29),
 datetime.date(2016, 5, 30),
 datetime.date(2016, 5, 31),
 datetime.date(2016, 6, 1),
 datetime.date(2016, 6, 2),
 datetime.date(2016, 6, 3),
 datetime.date(2016, 6, 4),
 datetime.date(2016, 6, 5),
 datetime.date(2016, 6, 6),
 datetime.date(2016, 6, 7),
 datetime.date(2016, 6, 8),
 datetime.date(2016, 6, 9),
 datetime.date(2016, 6, 10),
 datetime.date(2016, 6, 11),
 datetime.date(2016, 6, 12),
 datetime.date(2016, 6, 13),
 datetime.date(2016, 6, 14),
 datetime.date(2016, 6, 15),
 datetime.date(2016, 6, 16),
 datetime.date(2016, 6, 17),
 datetime.date(2016, 6, 18),
 datetime.date(2016, 6, 19),
 datetime.date(2016, 6, 20),
 datetime.date(2016, 6, 21),
 datetime.date(2016, 6, 22),
 datetime.date(2016, 6, 23),
 datetime.date(2016, 6, 24),
 datetime.date(2016, 6, 25),
 datetime.date(2016, 6, 26),
 datetime.date(2016, 6, 27),
 datetime.date(2016, 6, 28),
 datetime.date(2016, 6, 29),
 datetime.date(2016, 6, 30),
 datetime.date(2016, 7, 1),
 datetime.date(2016, 7, 2),
 datetime.date(2016, 7, 3),
 datetime.date(2016, 7, 4),
 datetime.date(2016, 7, 5),
 datetime.date(2016, 7, 6),
 datetime.date(2016, 7, 7),
 datetime.date(2016, 7, 8),
 datetime.date(2016, 7, 9),
 datetime.date(2016, 7, 10),
 datetime.date(2016, 7, 11),
 datetime.date(2016, 7, 12),
 datetime.date(2016, 7, 13),
 datetime.date(2016, 7, 14),
 datetime.date(2016, 7, 15),
 datetime.date(2016, 7, 16),
 datetime.date(2016, 7, 17),
 datetime.date(2016, 7, 18),
 datetime.date(2016, 7, 19),
 datetime.date(2016, 7, 20),
 datetime.date(2016, 7, 21),
 datetime.date(2016, 7, 22),
 datetime.date(2016, 7, 23),
 datetime.date(2016, 7, 24),
 datetime.date(2016, 7, 25),
 datetime.date(2016, 7, 26),
 datetime.date(2016, 7, 27),
 datetime.date(2016, 7, 28),
 datetime.date(2016, 7, 29),
 datetime.date(2016, 7, 30),
 datetime.date(2016, 7, 31),
 datetime.date(2016, 8, 1),
 datetime.date(2016, 8, 2),
 datetime.date(2016, 8, 3),
 datetime.date(2016, 8, 4),
 datetime.date(2016, 8, 5),
 datetime.date(2016, 8, 6),
 datetime.date(2016, 8, 7),
 datetime.date(2016, 8, 8),
 datetime.date(2016, 8, 9),
 datetime.date(2016, 8, 10),
 datetime.date(2016, 8, 11),
 datetime.date(2016, 8, 12),
 datetime.date(2016, 8, 13),
 datetime.date(2016, 8, 14),
 datetime.date(2016, 8, 15),
 datetime.date(2016, 8, 16),
 datetime.date(2016, 8, 17),
 datetime.date(2016, 8, 18),
 datetime.date(2016, 8, 19),
 datetime.date(2016, 8, 20),
 datetime.date(2016, 8, 21),
 datetime.date(2016, 8, 22),
 datetime.date(2016, 8, 23),
 datetime.date(2016, 8, 24),
 datetime.date(2016, 8, 25),
 datetime.date(2016, 8, 26),
 datetime.date(2016, 8, 27),
 datetime.date(2016, 8, 28),
 datetime.date(2016, 8, 29),
 datetime.date(2016, 8, 30),
 datetime.date(2016, 8, 31),
 datetime.date(2016, 9, 1),
 datetime.date(2016, 9, 2),
 datetime.date(2016, 9, 3),
 datetime.date(2016, 9, 4),
 datetime.date(2016, 9, 5),
 datetime.date(2016, 9, 6),
 datetime.date(2016, 9, 7),
 datetime.date(2016, 9, 8),
 datetime.date(2016, 9, 9),
 datetime.date(2016, 9, 10),
 datetime.date(2016, 9, 11),
 datetime.date(2016, 9, 12),
 datetime.date(2016, 9, 13),
 datetime.date(2016, 9, 14),
 datetime.date(2016, 9, 15),
 datetime.date(2016, 9, 16),
 datetime.date(2016, 9, 17),
 datetime.date(2016, 9, 18),
 datetime.date(2016, 9, 19),
 datetime.date(2016, 9, 20),
 datetime.date(2016, 9, 21),
 datetime.date(2016, 9, 22),
 datetime.date(2016, 9, 23),
 datetime.date(2016, 9, 24),
 datetime.date(2016, 9, 25),
 datetime.date(2016, 9, 26),
 datetime.date(2016, 9, 27),
 datetime.date(2016, 9, 28),
 datetime.date(2016, 9, 29),
 datetime.date(2016, 9, 30),
 datetime.date(2016, 10, 1),
 datetime.date(2016, 10, 2),
 datetime.date(2016, 10, 3),
 datetime.date(2016, 10, 4),
 datetime.date(2016, 10, 5),
 datetime.date(2016, 10, 6),
 datetime.date(2016, 10, 7),
 datetime.date(2016, 10, 8),
 datetime.date(2016, 10, 9),
 datetime.date(2016, 10, 10),
 datetime.date(2016, 10, 11),
 datetime.date(2016, 10, 12),
 datetime.date(2016, 10, 13),
 datetime.date(2016, 10, 14),
 datetime.date(2016, 10, 15),
 datetime.date(2016, 10, 16),
 datetime.date(2016, 10, 17),
 datetime.date(2016, 10, 18),
 datetime.date(2016, 10, 19),
 datetime.date(2016, 10, 20),
 datetime.date(2016, 10, 21),
 datetime.date(2016, 10, 22),
 datetime.date(2016, 10, 23),
 datetime.date(2016, 10, 24),
 datetime.date(2016, 10, 25),
 datetime.date(2016, 10, 26),
 datetime.date(2016, 10, 27),
 datetime.date(2016, 10, 28),
 datetime.date(2016, 10, 29),
 datetime.date(2016, 10, 30),
 datetime.date(2016, 10, 31),
 datetime.date(2016, 11, 1),
 datetime.date(2016, 11, 2),
 datetime.date(2016, 11, 3),
 datetime.date(2016, 11, 4),
 datetime.date(2016, 11, 5),
 datetime.date(2016, 11, 6),
 datetime.date(2016, 11, 7),
 datetime.date(2016, 11, 8),
 datetime.date(2016, 11, 9),
 datetime.date(2016, 11, 10),
 datetime.date(2016, 11, 11),
 datetime.date(2016, 11, 12),
 datetime.date(2016, 11, 13),
 datetime.date(2016, 11, 14),
 datetime.date(2016, 11, 15),
 datetime.date(2016, 11, 16),
 datetime.date(2016, 11, 17),
 datetime.date(2016, 11, 18),
 datetime.date(2016, 11, 19),
 datetime.date(2016, 11, 20),
 datetime.date(2016, 11, 21),
 datetime.date(2016, 11, 22),
 datetime.date(2016, 11, 23),
 datetime.date(2016, 11, 24),
 datetime.date(2016, 11, 25),
 datetime.date(2016, 11, 26),
 datetime.date(2016, 11, 27),
 datetime.date(2016, 11, 28),
 datetime.date(2016, 11, 29),
 datetime.date(2016, 11, 30),
 datetime.date(2016, 12, 1),
 datetime.date(2016, 12, 2),
 datetime.date(2016, 12, 3),
 datetime.date(2016, 12, 4),
 datetime.date(2016, 12, 5),
 datetime.date(2016, 12, 6),
 datetime.date(2016, 12, 7),
 datetime.date(2016, 12, 8),
 datetime.date(2016, 12, 9),
 datetime.date(2016, 12, 10),
 datetime.date(2016, 12, 11),
 datetime.date(2016, 12, 12),
 datetime.date(2016, 12, 13),
 datetime.date(2016, 12, 14),
 datetime.date(2016, 12, 15),
 datetime.date(2016, 12, 16),
 datetime.date(2016, 12, 17),
 datetime.date(2016, 12, 18),
 datetime.date(2016, 12, 19),
 datetime.date(2016, 12, 20),
 datetime.date(2016, 12, 21),
 datetime.date(2016, 12, 22),
 datetime.date(2016, 12, 23),
 datetime.date(2016, 12, 24),
 datetime.date(2016, 12, 25),
 datetime.date(2016, 12, 26),
 datetime.date(2016, 12, 27),
 datetime.date(2016, 12, 28),
 datetime.date(2016, 12, 29),
 datetime.date(2016, 12, 30),
 datetime.date(2016, 12, 31),
 datetime.date(2017, 1, 1),
 datetime.date(2017, 1, 2),
 datetime.date(2017, 1, 3),
 datetime.date(2017, 1, 4),
 datetime.date(2017, 1, 5),
 datetime.date(2017, 1, 6),
 datetime.date(2017, 1, 7),
 datetime.date(2017, 1, 8),
 datetime.date(2017, 1, 9),
 datetime.date(2017, 1, 10),
 datetime.date(2017, 1, 11),
 datetime.date(2017, 1, 12),
 datetime.date(2017, 1, 13),
 datetime.date(2017, 1, 14),
 datetime.date(2017, 1, 15),
 datetime.date(2017, 1, 16),
 datetime.date(2017, 1, 17),
 datetime.date(2017, 1, 18),
 datetime.date(2017, 1, 19),
 datetime.date(2017, 1, 20),
 datetime.date(2017, 1, 21),
 datetime.date(2017, 1, 22),
 datetime.date(2017, 1, 23),
 datetime.date(2017, 1, 24),
 datetime.date(2017, 1, 25),
 datetime.date(2017, 1, 26),
 datetime.date(2017, 1, 27),
 datetime.date(2017, 1, 28),
 datetime.date(2017, 1, 29),
 datetime.date(2017, 1, 30),
 datetime.date(2017, 1, 31),
 datetime.date(2017, 2, 1),
 datetime.date(2017, 2, 2),
 datetime.date(2017, 2, 3),
 datetime.date(2017, 2, 4),
 datetime.date(2017, 2, 5),
 datetime.date(2017, 2, 6),
 datetime.date(2017, 2, 7),
 datetime.date(2017, 2, 8),
 datetime.date(2017, 2, 9),
 datetime.date(2017, 2, 10),
 datetime.date(2017, 2, 11),
 datetime.date(2017, 2, 12),
 datetime.date(2017, 2, 13),
 datetime.date(2017, 2, 14),
 datetime.date(2017, 2, 15),
 datetime.date(2017, 2, 16),
 datetime.date(2017, 2, 17),
 datetime.date(2017, 2, 18),
 datetime.date(2017, 2, 19),
 datetime.date(2017, 2, 20),
 datetime.date(2017, 2, 21),
 datetime.date(2017, 2, 22),
 datetime.date(2017, 2, 23),
 datetime.date(2017, 2, 24),
 datetime.date(2017, 2, 25),
 datetime.date(2017, 2, 26),
 datetime.date(2017, 2, 27),
 datetime.date(2017, 2, 28),
 datetime.date(2017, 3, 1),
 datetime.date(2017, 3, 2),
 datetime.date(2017, 3, 3),
 datetime.date(2017, 3, 4),
 datetime.date(2017, 3, 5),
 datetime.date(2017, 3, 6),
 datetime.date(2017, 3, 7),
 datetime.date(2017, 3, 8),
 datetime.date(2017, 3, 9),
 datetime.date(2017, 3, 10),
 datetime.date(2017, 3, 11),
 datetime.date(2017, 3, 12),
 datetime.date(2017, 3, 13),
 datetime.date(2017, 3, 14),
 datetime.date(2017, 3, 15),
 datetime.date(2017, 3, 16),
 datetime.date(2017, 3, 17),
 datetime.date(2017, 3, 18),
 datetime.date(2017, 3, 19),
 datetime.date(2017, 3, 20),
 datetime.date(2017, 3, 21),
 datetime.date(2017, 3, 22),
 datetime.date(2017, 3, 23),
 datetime.date(2017, 3, 24),
 datetime.date(2017, 3, 25),
 datetime.date(2017, 3, 26),
 datetime.date(2017, 3, 27),
 datetime.date(2017, 3, 28),
 datetime.date(2017, 3, 29),
 datetime.date(2017, 3, 30),
 datetime.date(2017, 3, 31),
 datetime.date(2017, 4, 1),
 datetime.date(2017, 4, 2),
 datetime.date(2017, 4, 3),
 datetime.date(2017, 4, 4),
 datetime.date(2017, 4, 5),
 datetime.date(2017, 4, 6),
 datetime.date(2017, 4, 7),
 datetime.date(2017, 4, 8),
 datetime.date(2017, 4, 9),
 datetime.date(2017, 4, 10),
 datetime.date(2017, 4, 11),
 datetime.date(2017, 4, 12),
 datetime.date(2017, 4, 13),
 datetime.date(2017, 4, 14),
 datetime.date(2017, 4, 15),
 datetime.date(2017, 4, 16),
 datetime.date(2017, 4, 17),
 datetime.date(2017, 4, 18),
 datetime.date(2017, 4, 19),
 datetime.date(2017, 4, 20),
 datetime.date(2017, 4, 21),
 datetime.date(2017, 4, 22),
 datetime.date(2017, 4, 23),
 datetime.date(2017, 4, 24)]

In [8]:
url = 'https://openaq-data.s3.amazonaws.com/'

historical_dates= []
for x in datadays:
    historical_dates.append(x.strftime('%Y-%m-%d'))
    
historical_dates

['2016-04-25',
 '2016-04-26',
 '2016-04-27',
 '2016-04-28',
 '2016-04-29',
 '2016-04-30',
 '2016-05-01',
 '2016-05-02',
 '2016-05-03',
 '2016-05-04',
 '2016-05-05',
 '2016-05-06',
 '2016-05-07',
 '2016-05-08',
 '2016-05-09',
 '2016-05-10',
 '2016-05-11',
 '2016-05-12',
 '2016-05-13',
 '2016-05-14',
 '2016-05-15',
 '2016-05-16',
 '2016-05-17',
 '2016-05-18',
 '2016-05-19',
 '2016-05-20',
 '2016-05-21',
 '2016-05-22',
 '2016-05-23',
 '2016-05-24',
 '2016-05-25',
 '2016-05-26',
 '2016-05-27',
 '2016-05-28',
 '2016-05-29',
 '2016-05-30',
 '2016-05-31',
 '2016-06-01',
 '2016-06-02',
 '2016-06-03',
 '2016-06-04',
 '2016-06-05',
 '2016-06-06',
 '2016-06-07',
 '2016-06-08',
 '2016-06-09',
 '2016-06-10',
 '2016-06-11',
 '2016-06-12',
 '2016-06-13',
 '2016-06-14',
 '2016-06-15',
 '2016-06-16',
 '2016-06-17',
 '2016-06-18',
 '2016-06-19',
 '2016-06-20',
 '2016-06-21',
 '2016-06-22',
 '2016-06-23',
 '2016-06-24',
 '2016-06-25',
 '2016-06-26',
 '2016-06-27',
 '2016-06-28',
 '2016-06-29',
 '2016-06-30',
 '2016-07-01',
 '2016-07-02',
 '2016-07-03',
 '2016-07-04',
 '2016-07-05',
 '2016-07-06',
 '2016-07-07',
 '2016-07-08',
 '2016-07-09',
 '2016-07-10',
 '2016-07-11',
 '2016-07-12',
 '2016-07-13',
 '2016-07-14',
 '2016-07-15',
 '2016-07-16',
 '2016-07-17',
 '2016-07-18',
 '2016-07-19',
 '2016-07-20',
 '2016-07-21',
 '2016-07-22',
 '2016-07-23',
 '2016-07-24',
 '2016-07-25',
 '2016-07-26',
 '2016-07-27',
 '2016-07-28',
 '2016-07-29',
 '2016-07-30',
 '2016-07-31',
 '2016-08-01',
 '2016-08-02',
 '2016-08-03',
 '2016-08-04',
 '2016-08-05',
 '2016-08-06',
 '2016-08-07',
 '2016-08-08',
 '2016-08-09',
 '2016-08-10',
 '2016-08-11',
 '2016-08-12',
 '2016-08-13',
 '2016-08-14',
 '2016-08-15',
 '2016-08-16',
 '2016-08-17',
 '2016-08-18',
 '2016-08-19',
 '2016-08-20',
 '2016-08-21',
 '2016-08-22',
 '2016-08-23',
 '2016-08-24',
 '2016-08-25',
 '2016-08-26',
 '2016-08-27',
 '2016-08-28',
 '2016-08-29',
 '2016-08-30',
 '2016-08-31',
 '2016-09-01',
 '2016-09-02',
 '2016-09-03',
 '2016-09-04',
 '2016-09-05',
 '2016-09-06',
 '2016-09-07',
 '2016-09-08',
 '2016-09-09',
 '2016-09-10',
 '2016-09-11',
 '2016-09-12',
 '2016-09-13',
 '2016-09-14',
 '2016-09-15',
 '2016-09-16',
 '2016-09-17',
 '2016-09-18',
 '2016-09-19',
 '2016-09-20',
 '2016-09-21',
 '2016-09-22',
 '2016-09-23',
 '2016-09-24',
 '2016-09-25',
 '2016-09-26',
 '2016-09-27',
 '2016-09-28',
 '2016-09-29',
 '2016-09-30',
 '2016-10-01',
 '2016-10-02',
 '2016-10-03',
 '2016-10-04',
 '2016-10-05',
 '2016-10-06',
 '2016-10-07',
 '2016-10-08',
 '2016-10-09',
 '2016-10-10',
 '2016-10-11',
 '2016-10-12',
 '2016-10-13',
 '2016-10-14',
 '2016-10-15',
 '2016-10-16',
 '2016-10-17',
 '2016-10-18',
 '2016-10-19',
 '2016-10-20',
 '2016-10-21',
 '2016-10-22',
 '2016-10-23',
 '2016-10-24',
 '2016-10-25',
 '2016-10-26',
 '2016-10-27',
 '2016-10-28',
 '2016-10-29',
 '2016-10-30',
 '2016-10-31',
 '2016-11-01',
 '2016-11-02',
 '2016-11-03',
 '2016-11-04',
 '2016-11-05',
 '2016-11-06',
 '2016-11-07',
 '2016-11-08',
 '2016-11-09',
 '2016-11-10',
 '2016-11-11',
 '2016-11-12',
 '2016-11-13',
 '2016-11-14',
 '2016-11-15',
 '2016-11-16',
 '2016-11-17',
 '2016-11-18',
 '2016-11-19',
 '2016-11-20',
 '2016-11-21',
 '2016-11-22',
 '2016-11-23',
 '2016-11-24',
 '2016-11-25',
 '2016-11-26',
 '2016-11-27',
 '2016-11-28',
 '2016-11-29',
 '2016-11-30',
 '2016-12-01',
 '2016-12-02',
 '2016-12-03',
 '2016-12-04',
 '2016-12-05',
 '2016-12-06',
 '2016-12-07',
 '2016-12-08',
 '2016-12-09',
 '2016-12-10',
 '2016-12-11',
 '2016-12-12',
 '2016-12-13',
 '2016-12-14',
 '2016-12-15',
 '2016-12-16',
 '2016-12-17',
 '2016-12-18',
 '2016-12-19',
 '2016-12-20',
 '2016-12-21',
 '2016-12-22',
 '2016-12-23',
 '2016-12-24',
 '2016-12-25',
 '2016-12-26',
 '2016-12-27',
 '2016-12-28',
 '2016-12-29',
 '2016-12-30',
 '2016-12-31',
 '2017-01-01',
 '2017-01-02',
 '2017-01-03',
 '2017-01-04',
 '2017-01-05',
 '2017-01-06',
 '2017-01-07',
 '2017-01-08',
 '2017-01-09',
 '2017-01-10',
 '2017-01-11',
 '2017-01-12',
 '2017-01-13',
 '2017-01-14',
 '2017-01-15',
 '2017-01-16',
 '2017-01-17',
 '2017-01-18',
 '2017-01-19',
 '2017-01-20',
 '2017-01-21',
 '2017-01-22',
 '2017-01-23',
 '2017-01-24',
 '2017-01-25',
 '2017-01-26',
 '2017-01-27',
 '2017-01-28',
 '2017-01-29',
 '2017-01-30',
 '2017-01-31',
 '2017-02-01',
 '2017-02-02',
 '2017-02-03',
 '2017-02-04',
 '2017-02-05',
 '2017-02-06',
 '2017-02-07',
 '2017-02-08',
 '2017-02-09',
 '2017-02-10',
 '2017-02-11',
 '2017-02-12',
 '2017-02-13',
 '2017-02-14',
 '2017-02-15',
 '2017-02-16',
 '2017-02-17',
 '2017-02-18',
 '2017-02-19',
 '2017-02-20',
 '2017-02-21',
 '2017-02-22',
 '2017-02-23',
 '2017-02-24',
 '2017-02-25',
 '2017-02-26',
 '2017-02-27',
 '2017-02-28',
 '2017-03-01',
 '2017-03-02',
 '2017-03-03',
 '2017-03-04',
 '2017-03-05',
 '2017-03-06',
 '2017-03-07',
 '2017-03-08',
 '2017-03-09',
 '2017-03-10',
 '2017-03-11',
 '2017-03-12',
 '2017-03-13',
 '2017-03-14',
 '2017-03-15',
 '2017-03-16',
 '2017-03-17',
 '2017-03-18',
 '2017-03-19',
 '2017-03-20',
 '2017-03-21',
 '2017-03-22',
 '2017-03-23',
 '2017-03-24',
 '2017-03-25',
 '2017-03-26',
 '2017-03-27',
 '2017-03-28',
 '2017-03-29',
 '2017-03-30',
 '2017-03-31',
 '2017-04-01',
 '2017-04-02',
 '2017-04-03',
 '2017-04-04',
 '2017-04-05',
 '2017-04-06',
 '2017-04-07',
 '2017-04-08',
 '2017-04-09',
 '2017-04-10',
 '2017-04-11',
 '2017-04-12',
 '2017-04-13',
 '2017-04-14',
 '2017-04-15',
 '2017-04-16',
 '2017-04-17',
 '2017-04-18',
 '2017-04-19',
 '2017-04-20',
 '2017-04-21',
 '2017-04-22',
 '2017-04-23',
 '2017-04-24']

In [10]:
# for day in historical_dates:
historical_url = url + '2016-04-25' + '.csv'
df = pd.read_csv(historical_url)
df = df.drop(columns=['location', 'local', 'country', 'latitude', 'longitude', 'unit', 'attribution'])
df_delhi = df[df['city'] == 'Delhi']
df_delhi

        city                       utc parameter    value
5      Delhi  2016-04-25T00:00:00.000Z        o3     4.32
6      Delhi  2016-04-25T00:00:00.000Z        co  1150.00
236    Delhi  2016-04-25T00:00:00.000Z       no2    30.85
3082   Delhi  2016-04-25T00:00:00.000Z      pm10   158.00
3083   Delhi  2016-04-25T00:00:00.000Z      pm25    37.00
...      ...                       ...       ...      ...
94829  Delhi  2016-04-25T23:30:00.000Z       no2    38.49
94847  Delhi  2016-04-25T23:45:00.000Z        co   540.00
94874  Delhi  2016-04-25T23:45:00.000Z        o3    28.06
94875  Delhi  2016-04-25T23:45:00.000Z        co  1840.00
94876  Delhi  2016-04-25T23:45:00.000Z       no2    34.33

[822 rows x 4 columns]

In [ ]:
# parameters = [‘o3’, ‘co’, ‘no2’, ‘pm10’, ‘pm25’]

In [ ]:
#Table names - Climate_db, Air_Quality_db
#Other considerations
#Index air_quality in date, New "o3, co, no2, pm 10, pm 25", value
    #Rename UTC to Date & format date
#Weather - keep all data
    #Cleaned data to align with time period "4/25/2016 - 4/24/2017"
#average 24hr timeframe or pick certain point of the day
#PK = Date

Create database connection

In [ ]:
connection_string = "postgres:postgres@localhost:5432/Delhi_db"
engine = create_engine(f'postgresql://{connection_string}')

In [ ]:
# Confirm tables
engine.table_names()

Load DataFrames into database

In [ ]:
air_quality.to_sql(name='premise', con=engine, if_exists='append', index=True)

In [ ]:
climate.to_sql(name='county', con=engine, if_exists='append', index=True)

Visualization of Dataset - Bar Chart

In [ ]:
merged_df= pd.merge(climate_df, pollutant_df, how="outer", on="date")
merged_df.head()

In [ ]:
plt.bar(merged_df["humidity", "parameters"], title="not sure yet", color="red")